--- !ruby/object:VR_ENV
browser: firefox
width: 1366
height: 686
panel_pos: 360
backup_path: /home/rafaelim
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- /home/rafaelim/Documents/Projects/Simulation/Untitled
open_folders:
- /home/rafaelim/Documents/Projects/Simulation
- /home/rafaelim/Documents/Projects/Simulation/bin
- /home/rafaelim/Documents/Projects/Simulation/demos
- /home/rafaelim/Documents/Projects/Simulation/demos/config
- /home/rafaelim/Documents/Projects/Simulation/demos/lib
current_file: /home/rafaelim/Documents/Projects/Simulation/Untitled
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
